#!/usr/bin/env python3
"""Generate the Windows VERSIONINFO resource used by PyInstaller.

The values come from ``audiflix.__version__`` so the properties shown in the
Windows file dialog can never drift away from the package version. The spec
file calls :func:`write_version_file` during the build.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

TEMPLATE = """# Auto-generated by tools/version_info.py - do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={tuple_version},
    prodvers={tuple_version},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [
          StringStruct('CompanyName', '{company}'),
          StringStruct('FileDescription', '{description}'),
          StringStruct('FileVersion', '{version}'),
          StringStruct('InternalName', 'audiflix'),
          StringStruct('LegalCopyright', '{copyright}'),
          StringStruct('OriginalFilename', 'audiflix.exe'),
          StringStruct('ProductName', '{product}'),
          StringStruct('ProductVersion', '{version}'),
        ],
      )
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])]),
  ],
)
"""

COMPANY = "Felix Steindorff"
PRODUCT = "Audiflix"
DESCRIPTION = "Accessible desktop client for Audiobookshelf"
COPYRIGHT = "Copyright (c) 2026 Felix Steindorff - MIT License"


def read_version() -> str:
    """Read ``__version__`` from the package without importing wx or requests."""
    source = (ROOT / "src" / "audiflix" / "__init__.py").read_text(encoding="utf-8")
    match = re.search(r'^__version__\s*=\s*"([^"]+)"', source, re.MULTILINE)
    if not match:
        raise RuntimeError("Could not find __version__ in src/audiflix/__init__.py")
    return match.group(1)


def version_tuple(version: str) -> tuple[int, int, int, int]:
    """'0.1.0' -> (0, 1, 0, 0); trailing pre-release parts are ignored."""
    numbers = [int(part) for part in re.findall(r"\d+", version)][:4]
    numbers += [0] * (4 - len(numbers))
    return tuple(numbers)  # type: ignore[return-value]


def write_version_file(path: Path | str, version: str | None = None) -> Path:
    version = version or read_version()
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        TEMPLATE.format(
            tuple_version=version_tuple(version),
            version=version,
            company=COMPANY,
            product=PRODUCT,
            description=DESCRIPTION,
            copyright=COPYRIGHT,
        ),
        encoding="utf-8",
    )
    return target


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    target = Path(argv[0]) if argv else ROOT / "build" / "version_info.txt"
    written = write_version_file(target)
    print(f"Wrote {written} for version {read_version()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
